-- Schema changes required for Phase 1 of the "company brain" work
-- (docs/scope-company-brain.md). Applied to the live project
-- (wzyvbtzxxdcxgvbkcqmt) via mcp__Supabase__apply_migration.
--
-- Two new tables, both company-scoped exactly like every other
-- company-scoped table in this schema (roster, sops, sites, equipment,
-- etc.) — company_id FK, RLS enabled with zero policies (deny-by-default
-- backstop per README.md), all real access-control done in api/*.js
-- against the session-verified company_id, not at the DB layer.
--
-- id/company_id are `bigint generated by default as identity` /
-- `bigint references companies(id)`, NOT uuid — confirmed against the
-- live schema before applying (every existing table, including
-- companies.id itself, uses bigint identity columns; the first version of
-- this file assumed uuid throughout, which would have failed outright on
-- the company_id foreign key type mismatch. Caught and fixed before
-- applying, not after.).

create table if not exists company_profiles (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  status text not null default 'draft', -- 'draft' | 'confirmed' — draft until an admin reviews it, same pattern as onboarding's equipment_draft/sop_drafts
  industry_inference text, -- e.g. "earthworks / heavy civil" — inferred at onboarding from units_list, uploaded SOPs, and company name only (no external/web lookups)
  equipment_summary text,
  terminology_notes text,
  hazard_emphasis jsonb not null default '[]'::jsonb, -- [{ category, note }] — company-specific emphasis learned from signals over time. NEVER read as a risk-rating override — generation-time code must only use this to bias which hazards/terminology get surfaced, never to lower a risk level or skip a required baseline category (docs/scope-company-brain.md "Safety floor").
  last_summarized_at timestamptz, -- set by the Phase 4 batch job when it last rolled signals into hazard_emphasis/terminology_notes
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- One profile per company.
create unique index if not exists company_profiles_company_id_idx
  on company_profiles (company_id);

alter table company_profiles enable row level security;

create table if not exists company_signals (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  source_type text not null, -- 'flha_edit' | 'toolbox_talk' | 'incident' | 'near_miss'
  source_id text, -- id of the originating row (flhas.id, etc.), stringified. Source tables are actually all bigint (see the id/company_id note above), but this column has no FK constraint — it's informational only, and api/flhas.js/logs.js/reports.js already write it as String(newId), so text is kept rather than switched to bigint purely to avoid an unnecessary code change.
  signal_json jsonb not null, -- structured payload: for flha_edit, a diff of hazards added/removed/risk-changed between AI output and what was submitted; for toolbox_talk/incident/near_miss, topic/category
  created_at timestamptz not null default now()
);

-- Append-only by design (Phase 3 note in docs/scope-company-brain.md) —
-- no updated_at, rows are never mutated after insert.

create index if not exists company_signals_company_id_created_at_idx
  on company_signals (company_id, created_at desc);

alter table company_signals enable row level security;
