-- docs/schema/company-portal-phase5-migration.sql
--
-- Company Portal phase 5 (FORA Company Portal — Build Spec, "Question-level
-- escalation" — the last of the 5 build-order phases; NOT part of the v1
-- cut line, which is phases 1-4 per the 2026-09-28 Boardroom decision).
--
-- Adds the two pieces phase 2's migration deliberately deferred:
--   - portal_questions.escalation_department / escalation_trigger_value
--   - portal_escalations, a narrow table that carries only the flagged
--     question + answer + status, never the whole document (spec:
--     "Deliberately narrow, carries only the flagged question/answer +
--     status, not the whole document").
--
-- Escalation is restricted to the field types where a discrete flagged
-- value actually makes sense to auto-detect: yesno, dropdown, multiselect
-- (see server-lib/portalFieldTypes.js's ESCALATABLE_FIELD_TYPES). The spec
-- doesn't literally enumerate this, but every escalation example it gives
-- ("answer = fail/flagged", "a pass/fail column") is this shape — free
-- text/number/date/signature/file_upload have no fixed "flagged" value to
-- compare against, so the builder UI and the AI draft prompt both only
-- offer escalation on those three types.
--
-- question_text and answer_value are captured on the escalation row at
-- creation time, not looked up live through question_id/record_id at read
-- time. This matters because publish_document does a wholesale
-- delete-and-reinsert of portal_questions on a republish (see phase 2's
-- migration comment) — an escalation raised against the old version of a
-- document must keep reading correctly even after the question row that
-- triggered it is gone. question_id is kept for traceability where it
-- still resolves, set null rather than cascaded when the question is
-- deleted out from under it.

alter table public.portal_questions
  add column if not exists escalation_department text,
  add column if not exists escalation_trigger_value text;

create table if not exists public.portal_escalations (
  id bigint generated by default as identity primary key,
  record_id bigint not null references public.portal_records(id) on delete cascade,
  document_id bigint not null references public.portal_documents(id) on delete cascade,
  question_id bigint references public.portal_questions(id) on delete set null,
  question_text text not null,
  answer_value text not null,
  -- Validated in application code against server-lib/portalDepartments.js,
  -- same reasoning as every other departments-array/text column in this
  -- feature — no DB check constraint so the department list can grow
  -- without a migration.
  target_department text not null,
  status text not null default 'open' check (status in ('open', 'actioned')),
  actioned_by_roster_id bigint references public.roster(id),
  actioned_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists portal_escalations_document_id_idx on public.portal_escalations(document_id);
create index if not exists portal_escalations_record_id_idx on public.portal_escalations(record_id);
create index if not exists portal_escalations_status_idx on public.portal_escalations(status);

alter table public.portal_escalations enable row level security;

-- ── Verification ─────────────────────────────────────────────────────────
--
-- select column_name from information_schema.columns
-- where table_name = 'portal_questions' and column_name like 'escalation_%';
--
-- select relname, relrowsecurity from pg_class
-- where relname = 'portal_escalations' and relnamespace = 'public'::regnamespace::oid;
--
-- ── Rollback ─────────────────────────────────────────────────────────────
-- drop table if exists public.portal_escalations;
-- alter table public.portal_questions
--   drop column if exists escalation_department,
--   drop column if exists escalation_trigger_value;
