-- docs/schema/company-portal-phase2-migration.sql
--
-- Company Portal phase 2 (FORA Company Portal — Build Spec, "Document
-- engine v2"). Generalizes api/customforms.js's yes/no-only
-- custom_forms/custom_form_questions/custom_form_records/custom_form_answers
-- into a Portal-specific set of tables that support the 8 field types in
-- the spec's "Field types and document engine" table. This does NOT touch
-- or migrate custom_forms — that stays exactly as it is for companies
-- already using it; Portal documents are a parallel, separate feature,
-- per the spec's "Different from existing FORA modules" note.
--
-- Deliberately excluded from this migration (phase 5, sequenced last, not
-- built yet): escalation_department / escalation_condition on
-- portal_questions, and the portal_escalations table. Adding them later is
-- a plain ALTER + CREATE TABLE, same shape as every other additive
-- migration in this file — nothing here has to be designed around that in
-- advance.
--
-- portal_documents.departments and .category are schema decisions made now
-- (Dillon's call, 2026-09-29) even though the BEHAVIOR that reads them
-- (dashboard filtering + notification email for departments; the Platform
-- Analytics rollup for category) is phase 3 and later — both are
-- intrinsic to what a document IS, not to how it's routed, so adding them
-- now means phase 3 only has to build behavior, not touch this schema
-- again.

create table if not exists public.portal_documents (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  title text not null,
  icon text,
  -- Free text, validated only for length here — the spec's autocomplete
  -- (matching "Vehicle Pre-Trip Inspection" to "Pre-Trip Vehicle Check")
  -- is Dillon's own judgment call at build time, not a taxonomy the
  -- database enforces. See server-lib/portalFieldTypes.js for the client
  -- autocomplete source.
  category text,
  -- Same array-not-constraint reasoning as roster.departments
  -- (docs/schema/roster-departments-migration.sql): validated in
  -- application code against server-lib/portalDepartments.js so the list
  -- can grow without a migration.
  departments text[] not null default '{}',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists portal_documents_company_id_idx on public.portal_documents(company_id);

create table if not exists public.portal_questions (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.portal_documents(id) on delete cascade,
  question_text text not null,
  -- Validated in application code against
  -- server-lib/portalFieldTypes.js's PORTAL_FIELD_TYPES, same reasoning as
  -- departments above — the check constraint below is a backstop against a
  -- row written outside the API, not the primary gate.
  field_type text not null check (field_type in ('yesno', 'short_text', 'number', 'date', 'dropdown', 'multiselect', 'signature', 'file_upload')),
  -- Dropdown/multiselect choices, e.g. ["Pass","Fail","N/A"]. Null for
  -- every other field type.
  options jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists portal_questions_document_id_idx on public.portal_questions(document_id);

create table if not exists public.portal_records (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.portal_documents(id),
  site_id bigint not null references public.sites(id),
  submitted_by text not null,
  -- Author stamping, same pattern/column shape as
  -- custom_form_records.submitted_by_roster_id
  -- (docs/schema/roster-attribution-migration.sql) — server-lib/authorStamp.js's
  -- authorRosterId(session), never client input.
  submitted_by_roster_id bigint references public.roster(id),
  ai_summary text,
  pdf_url text,
  status text not null default 'complete',
  -- Idempotency, same as custom_form_records.client_submission_id —
  -- protects the offline-queue retry path from creating a duplicate
  -- record when a resubmit both saved AND the success response was lost.
  client_submission_id text,
  created_at timestamptz not null default now()
);
create index if not exists portal_records_document_id_idx on public.portal_records(document_id);
create index if not exists portal_records_site_id_idx on public.portal_records(site_id);
create unique index if not exists portal_records_client_submission_id_idx
  on public.portal_records(document_id, client_submission_id)
  where client_submission_id is not null;

create table if not exists public.portal_answers (
  id bigint generated by default as identity primary key,
  record_id bigint not null references public.portal_records(id) on delete cascade,
  question_id bigint not null references public.portal_questions(id),
  -- Which of these is populated depends on the question's field_type:
  --   yesno            -> value_text ('yes' | 'no'), notes on 'no'
  --   short_text       -> value_text
  --   number           -> value_text (stored as text; parsed on read)
  --   date             -> value_text (ISO date string)
  --   dropdown         -> value_text (the selected option)
  --   multiselect      -> value_json (array of selected options)
  --   signature        -> file_url (signed upload receipt, portal-attachments bucket)
  --   file_upload      -> file_url (signed upload receipt, portal-attachments bucket)
  value_text text,
  value_json jsonb,
  file_url text,
  notes text,
  created_at timestamptz not null default now(),
  unique (record_id, question_id)
);
create index if not exists portal_answers_record_id_idx on public.portal_answers(record_id);

alter table public.portal_documents enable row level security;
alter table public.portal_questions enable row level security;
alter table public.portal_records enable row level security;
alter table public.portal_answers enable row level security;

-- ── Verification ─────────────────────────────────────────────────────────
--
-- select table_name from information_schema.tables
-- where table_schema = 'public' and table_name like 'portal_%';
--
-- select relname, relrowsecurity from pg_class
-- where relname like 'portal_%' and relnamespace = 'public'::regnamespace::oid;
--
-- ── Rollback ─────────────────────────────────────────────────────────────
-- drop table if exists public.portal_answers;
-- drop table if exists public.portal_records;
-- drop table if exists public.portal_questions;
-- drop table if exists public.portal_documents;
