-- docs/schema/company-portal-phase4-migration.sql
--
-- Company Portal phase 4 (FORA Company Portal — Build Spec, "Assignment +
-- compliance"): assignment rules, due dates, per-person completion
-- tracking, and a rollup view.
--
-- Design note on "status" (not started/submitted/overdue): deliberately
-- NOT a stored column on portal_assignments. It's derived at read time in
-- api/portal.js from whether a matching portal_records row exists and how
-- due_at compares to now() — a stored status column would need to be kept
-- in sync with portal_records on every submission and would drift the
-- first time something wrote one but not the other. Same reasoning as
-- portal_records.status not needing a "gated" value the way
-- company_document_settings does.
--
-- Design note on "role/group/individual/everyone" targeting (spec
-- wording): built as `target_type` in ('everyone', 'role', 'individual').
-- "Group" is not a separate target here — this app's only per-person
-- grouping concept below the whole roster is `roster.departments`
-- (phase 1), and that column exists ONLY on supervisor-tier rows (see
-- docs/schema/roster-departments-migration.sql), so a document assigned
-- to "everyone in Safety" cannot include workers, who hold no department.
-- Rather than build a targeting concept that silently only ever reaches
-- supervisors, department-based assignment targeting is left out of this
-- migration; 'role' (worker | supervisor) is the closest built primitive
-- to the spec's "group". Worth reopening if a real customer needs
-- department-scoped assignment once workers have some equivalent grouping.

create table if not exists public.portal_assignment_rules (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.portal_documents(id) on delete cascade,
  target_type text not null check (target_type in ('everyone', 'role', 'individual')),
  -- Only one of these is set, matching target_type. Both nullable rather
  -- than a check constraint tying them to target_type — application code
  -- (api/portal.js) is the single writer and already enforces the pairing.
  target_role text check (target_role in ('worker', 'supervisor')),
  target_roster_id bigint references public.roster(id),
  -- Days from assignment creation until due. Null = no due date (the
  -- spec's "opt-out at setup" — due dates default on, so a rule is
  -- created WITH a due_days value unless the admin explicitly clears it).
  due_days integer,
  -- The spec's "auto-applies to new hires" — read by
  -- server-lib/portalAssignments.js's applyRulesToNewRosterMember, called
  -- from api/companydata.js's add_roster_member/onboard_new_employee.
  auto_apply_new_hires boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists portal_assignment_rules_document_id_idx on public.portal_assignment_rules(document_id);

create table if not exists public.portal_assignments (
  id bigint generated by default as identity primary key,
  -- Nullable: an assignment can come from a rule (bulk) or an individual
  -- one-off override with no rule behind it (the spec's "or an individual
  -- override").
  rule_id bigint references public.portal_assignment_rules(id) on delete set null,
  document_id bigint not null references public.portal_documents(id) on delete cascade,
  roster_id bigint not null references public.roster(id),
  due_at timestamptz,
  created_at timestamptz not null default now(),
  -- One assignment per person per document — re-running a rule against an
  -- already-covered person is a no-op, not a duplicate row.
  unique (document_id, roster_id)
);
create index if not exists portal_assignments_document_id_idx on public.portal_assignments(document_id);
create index if not exists portal_assignments_roster_id_idx on public.portal_assignments(roster_id);

alter table public.portal_assignment_rules enable row level security;
alter table public.portal_assignments enable row level security;

-- ── Verification ─────────────────────────────────────────────────────────
--
-- select table_name from information_schema.tables
-- where table_schema = 'public' and table_name like 'portal_assignment%';
--
-- ── Rollback ─────────────────────────────────────────────────────────────
-- drop table if exists public.portal_assignments;
-- drop table if exists public.portal_assignment_rules;
