-- docs/schema/document-notifications-migration.sql
--
-- Notification routing, PR 1. NOT YET APPLIED: needs Dillon's yes first.
--
-- One row = "this company has decided how <document_key> notifies people".
-- No row means notifications are OFF for that document, which is also what
-- `enabled = false` means: nothing changes for a company until its Owner turns
-- a document on.
--
--   document_key      a built-in key ('flha', 'incident', ...) or
--                     'custom_<formId>'. The same key space as
--                     document_assignments. Portal documents already email
--                     their own departments (api/portal.js) and are not
--                     routed through this table.
--   enabled           the Owner's Notify switch for this document.
--   extra_roster_ids  "always notify these people" for this document, on top
--                     of whoever the visibility rules already reach. Roster
--                     ids of the same company; the application checks each one
--                     is an active member of that company before using it.
--
-- Who is notified is NOT stored here. It is worked out per record from the
-- same visibility rules that decide who can open it (server-lib/
-- documentAccess.js recordInScope, server-lib/leadAccess.js inCrew), with the
-- Account Owner as the fallback. See server-lib/notifyRouting.js.

create table if not exists public.document_notifications (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  document_key text not null,
  enabled boolean not null default false,
  extra_roster_ids bigint[] not null default '{}',
  updated_by bigint references public.roster(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique (company_id, document_key),
  check (document_key ~ '^(flha|inspection|toolbox|nearmiss|incident|daily|monthly|fuellog|custom_[0-9]+)$')
);

-- Deny-by-default backstop, same as every other table (README access model).
alter table public.document_notifications enable row level security;

-- Cooldown state. One row per (company, document, person): when that person was
-- last emailed about that document, and how many notices were held back since.
-- A person is emailed about a document at most once per cooldown window (10
-- minutes, server-lib/notifyRouting.js); the notices held back are counted and
-- reported in their next email ("N more since your last notice"). This is what
-- stops one worker looping submits from flooding inboxes or burning the
-- shared sender's Resend quota. It holds no report content and no address.
create table if not exists public.document_notification_state (
  company_id bigint not null references public.companies(id) on delete cascade,
  document_key text not null,
  roster_id bigint not null references public.roster(id) on delete cascade,
  last_sent_at timestamptz not null default now(),
  suppressed_count integer not null default 0 check (suppressed_count >= 0),
  primary key (company_id, document_key, roster_id)
);

alter table public.document_notification_state enable row level security;

-- ── Verification ─────────────────────────────────────────────────────────
-- select column_name from information_schema.columns
--   where table_schema = 'public' and table_name = 'document_notifications';
-- select relrowsecurity from pg_class where oid = 'public.document_notifications'::regclass;
-- select relrowsecurity from pg_class where oid = 'public.document_notification_state'::regclass;
--
-- ── Rollback ─────────────────────────────────────────────────────────────
-- drop table if exists public.document_notification_state;
-- drop table if exists public.document_notifications;
