-- docs/schema/document-assignments-migration.sql
--
-- Document assignments, step 5 PR 1. NOT YET APPLIED: run it in the
-- Supabase dashboard SQL editor (MCP writes and DDL have been timing out).
--
-- Departments and divisions are routing, filter and reporting TAGS. They are
-- not locks. Access changes only through an explicit row in this table, and
-- a row can only NARROW access, never widen it past module gating
-- (company_document_settings / server-lib/docKeyGate.js).
--
-- One row = "this audience may <action> this document".
--
--   document_key   a built-in key ('flha', 'incident', ...), 'custom_<formId>'
--                  or 'portal_<documentId>'. The same key space as
--                  company_document_settings, plus the Portal prefix.
--   audience_type  everyone | role | department | division | site | individual
--   audience_value role name | department key | division id | site id |
--                  roster id (all text). NULL only for 'everyone'.
--   action         'submit' (may fill the document in) or 'view' (may read
--                  its submissions; supervisor tier only, workers always see
--                  their own).
--   due_at         one absolute date, optional. Per-person completion is
--                  derived at read time from the author stamp on the
--                  submission, never stored (same reasoning as
--                  portal_assignments).
--   ended_at       soft end. A row is "active at T" when created_at <= T and
--                  (ended_at is null or ended_at > T). The server evaluates
--                  an offline-queued submission as of the time the worker
--                  filled it in, so removing or adding a row never drops a
--                  form already sitting on a phone. See
--                  server-lib/documentAccess.js.
--
-- No active RESTRICTING 'submit' rows for a document = everyone the module
-- allows may submit it, exactly as before. Same for 'view'. Tasks never
-- narrow anything.

create table if not exists public.document_assignments (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  document_key text not null,
  audience_type text not null
    check (audience_type in ('everyone', 'role', 'department', 'division', 'site', 'individual')),
  audience_value text,
  action text not null check (action in ('submit', 'view')),
  -- true: only the named audience may use the document (the Owner's call).
  -- false (the default): a TASK. It lands on the person's "assigned to you"
  -- list with a due date and takes nothing away from anyone else. Reading
  -- ('view') is always restricting: a view row that restricted nothing
  -- would mean nothing.
  restricts boolean not null default false,
  due_at timestamptz,
  created_by bigint references public.roster(id) on delete set null,
  created_at timestamptz not null default now(),
  ended_at timestamptz,
  check ((audience_type = 'everyone') = (audience_value is null)),
  -- Only documents whose handlers enforce assignments. A row on anything
  -- else (time clock, certifications, maintenance, ...) would be accepted
  -- and do nothing. Keep in step with ENFORCED_BUILTIN_KEYS in
  -- server-lib/documentAccess.js.
  check (document_key ~ '^(flha|inspection|toolbox|nearmiss|incident|daily|monthly|fuellog|custom_[0-9]+|portal_[0-9]+)$'),
  -- Portal supervisor reads are routed by department and ignore view rows.
  check (not (document_key like 'portal\_%' and action = 'view'))
  -- (action = 'submit' or restricts) is added below as a named constraint, so
  -- a fresh install and a catch-up end up identical.
);

-- Idempotent catch-up for a database that created the table from an earlier
-- version of this file (before `restricts` existed). `create table if not
-- exists` adds no column to a table that is already there, so the column and
-- its check are added separately. A no-op on a fresh install.
alter table public.document_assignments
  add column if not exists restricts boolean not null default false;
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.document_assignments'::regclass and conname = 'document_assignments_view_restricts'
  ) then
    alter table public.document_assignments
      add constraint document_assignments_view_restricts check (action = 'submit' or restricts);
  end if;
end $$;

create index if not exists document_assignments_company_doc_idx
  on public.document_assignments (company_id, document_key)
  where ended_at is null;

-- Deny-by-default backstop, same as every other table (README access model).
alter table public.document_assignments enable row level security;

-- A site belongs to at most one division (a division is the "business
-- unit"). Nullable: a site with no division behaves exactly as before. Nothing
-- in the app writes this column yet (the Owner screen that does ships in
-- PR 2, and it must check the division belongs to the site's own company; a
-- DB foreign key alone cannot). Until then it is set by hand.
alter table public.sites
  add column if not exists division_id bigint references public.company_divisions(id) on delete set null;

-- ── Verification ─────────────────────────────────────────────────────────
-- select column_name from information_schema.columns
--   where table_schema = 'public' and table_name = 'document_assignments';
-- select column_name from information_schema.columns
--   where table_schema = 'public' and table_name = 'sites' and column_name = 'division_id';
-- select relrowsecurity from pg_class where oid = 'public.document_assignments'::regclass;
--
-- ── Rollback ─────────────────────────────────────────────────────────────
-- alter table public.sites drop column if exists division_id;
-- drop table if exists public.document_assignments;
