-- Schema for Gatehouse: the transfer-station receipt module built for the
-- Red Deer County demo (see the proposal artifact from this planning
-- session). Runs on the same companies/session/auth backbone as FORA's
-- safety-document product, but with its own tables — a Gatehouse company
-- never touches flhas/sops/roster/equipment etc., and a safety company
-- never touches these.
--
-- APPLIED to the live FORA Supabase project (wzyvbtzxxdcxgvbkcqmt) via
-- mcp__Supabase__apply_migration, migration name "gatehouse_schema". The
-- id columns below are bigint (generated by default as identity), not
-- uuid — this file originally assumed uuid, which failed against
-- companies.id's real type (bigint) on first apply; kept here corrected
-- to match what's actually live, for anyone re-running this against a
-- fresh project.
--
-- Also applied: the private `gatehouse-uploads` storage bucket (cheque
-- photos); a follow-up migration "gatehouse_price_tier_addons" adding
-- is_addon (see the column comment below); and a demo seed — Red Deer
-- County (company_code REDDEERCOUNTY, company_id 16), Yankee Flats
-- (station_id 1) and Gaetz Creek (station_id 2), seeded with the
-- county's real rate schedule per Bylaw No. 1017/2025.

-- ── companies: which product a company is on ────────────────────────────
-- Existing FLHA-safety companies are unaffected (default keeps them on
-- 'safety'). Login/session code branches on this to route a company's
-- workers/supervisors to the Gatehouse UI instead of WorkerMenu/Dashboard.
alter table companies
  add column if not exists app_type text not null default 'safety';
-- values: 'safety' | 'gatehouse'

-- ── gatehouse_stations ───────────────────────────────────────────────────
-- One row per physical transfer station (e.g. Yankee Flats, Gaetz Creek).
-- next_receipt_number is the single source of truth for sequential,
-- gap-free receipt numbering within a business day — incremented
-- transactionally by log_transaction in api/gatehouse.js, never chosen by
-- the client. counter_business_date (added in a follow-up migration,
-- "gatehouse_daily_receipt_reset", applied) tracks which day that
-- sequence belongs to: the first transaction logged for a station on a
-- new business_date picks a fresh random 6-digit start (100000-999999)
-- rather than continuing the previous day's numbers, then counts up
-- gap-free from there same as before, all day.
create table if not exists gatehouse_stations (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  name text not null,
  next_receipt_number integer not null default 1,
  counter_business_date date,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists gatehouse_stations_company_id_idx
  on gatehouse_stations (company_id);

-- ── gatehouse_price_tiers ────────────────────────────────────────────────
-- The county's preset load-size price list. sort_order controls button
-- order on the booth screen. is_addon (added in a follow-up migration,
-- "gatehouse_price_tier_addons") distinguishes the base load-size options
-- (is_addon = false, exactly one picked per transaction) from stackable
-- surcharges like fridges/freezers or an untarped load (is_addon = true,
-- any number toggled alongside the base) — Red Deer County's real rate
-- schedule needs both: a load-size fee plus optional add-on surcharges in
-- the same visit, which must still be exactly one receipt number.
create table if not exists gatehouse_price_tiers (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  label text not null,
  price numeric(10,2) not null,
  sort_order integer not null default 0,
  is_addon boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists gatehouse_price_tiers_company_id_idx
  on gatehouse_price_tiers (company_id);

-- ── gatehouse_vehicles ───────────────────────────────────────────────────
-- Plate/email memory — looked up by plate at the booth so a returning
-- vehicle's email autofills instead of being re-typed.
create table if not exists gatehouse_vehicles (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  plate text not null,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, plate)
);

-- ── gatehouse_transactions ───────────────────────────────────────────────
-- One row per load: a priced tip, or a redirect (tier_id/amount/
-- payment_method all null, redirected = true). tier_label and price are
-- snapshotted onto the row at write time so a later price-list edit never
-- rewrites history. business_date is the operating day this belongs to
-- (set client-side from the booth's local clock at entry time, since a
-- transaction may sync hours after it was actually made offline) — daily
-- reports group on this, not created_at.
create table if not exists gatehouse_transactions (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  station_id bigint not null references gatehouse_stations(id) on delete cascade,
  receipt_number integer not null,
  business_date date not null,
  tier_id bigint references gatehouse_price_tiers(id),
  tier_label text,
  amount numeric(10,2),
  payment_method text, -- 'cash' | 'cheque' | null (redirected loads)
  cheque_photo_url text,
  plate text,
  vehicle_email text,
  redirected boolean not null default false,
  operator_name text,
  client_submission_id text not null,
  created_at timestamptz not null default now(),
  -- Receipt numbers restart (a fresh random 6-digit start) every business
  -- day per station — see counter_business_date below — so uniqueness has
  -- to include business_date, not just (company_id, station_id, receipt_
  -- number) as originally defined. Renamed to
  -- gatehouse_transactions_company_station_date_receipt_key in a
  -- follow-up migration, "gatehouse_daily_receipt_reset", applied.
  unique (company_id, station_id, business_date, receipt_number),
  unique (company_id, client_submission_id)
);
create index if not exists gatehouse_transactions_company_station_date_idx
  on gatehouse_transactions (company_id, station_id, business_date);

-- ── gatehouse_reconciliations ────────────────────────────────────────────
-- One row per station per business day: what Gatehouse expected in the
-- till from that day's cash transactions vs. what was actually counted.
-- reason (added in a follow-up migration, "gatehouse_reconciliation_reason")
-- matches the "Reason for Difference" line on the county's existing paper
-- Gaetz Creek Revenue Summary Report — same reconciliation shape, digital.
-- reviewed_by/reviewed_at (added in "gatehouse_reconciliation_review")
-- replace the paper form's two wet signatures with a two-step digital
-- signoff: submitted_by is the operator who counted the till, reviewed_by
-- is the supervisor who marked it reviewed afterward — deliberately not
-- the same action, and reviewed_by/reviewed_at are cleared by the API
-- whenever the operator resubmits, so an edited count always needs a
-- fresh review rather than silently keeping a stale one.
create table if not exists gatehouse_reconciliations (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  station_id bigint not null references gatehouse_stations(id) on delete cascade,
  business_date date not null,
  expected_cash numeric(10,2) not null,
  cash_counted numeric(10,2) not null,
  variance numeric(10,2) not null,
  reason text,
  submitted_by text,
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (company_id, station_id, business_date)
);

-- ── gatehouse_trailer_counts ─────────────────────────────────────────────
-- Manually entered for the demo (see the proposal's TRUX callout) — the
-- receiving facility's trailer count for a station/period, checked against
-- reported load volume for the same window. A live TRUX pull is a
-- phase-2 replacement for manual entry, not a schema change.
create table if not exists gatehouse_trailer_counts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  station_id bigint not null references gatehouse_stations(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  trailers_out integer not null,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);
create index if not exists gatehouse_trailer_counts_company_station_idx
  on gatehouse_trailer_counts (company_id, station_id);

-- ── RLS: deny-by-default backstop, matching every other table in this
-- project (see README's Architecture section) — api/gatehouse.js's
-- service-role key is the real access-control boundary, these policies
-- are the safety net if the anon key were ever queried directly.
alter table gatehouse_stations enable row level security;
alter table gatehouse_price_tiers enable row level security;
alter table gatehouse_vehicles enable row level security;
alter table gatehouse_transactions enable row level security;
alter table gatehouse_reconciliations enable row level security;
alter table gatehouse_trailer_counts enable row level security;

-- ── Storage: private bucket for cheque photos (already created) ─────────
-- insert into storage.buckets (id, name, public)
--   values ('gatehouse-uploads', 'gatehouse-uploads', false)
--   on conflict (id) do nothing;

-- ── Demo seed: Red Deer County (already applied — company_id 16,
-- stations 1/2) ──────────────────────────────────────────────────────────
-- Kept here for reference / re-running against a fresh project. Prices
-- are Red Deer County's real household waste rate schedule (Bylaw No.
-- 1017/2025) — editable afterward from FORA's Admin Panel → Pricing tab,
-- which is the intended way to change these going forward, not by
-- re-running this SQL.
--
-- with new_company as (
--   insert into companies (name, company_code, app_type)
--   values ('Red Deer County', 'REDDEERCOUNTY', 'gatehouse')
--   returning id
-- ),
-- new_stations as (
--   insert into gatehouse_stations (company_id, name)
--   select id, s.name from new_company, (values ('Yankee Flats'), ('Gaetz Creek')) as s(name)
--   returning id
-- )
-- insert into gatehouse_price_tiers (company_id, label, price, sort_order, is_addon)
-- select id, t.label, t.price, t.sort_order, t.is_addon
-- from new_company,
--   (values
--     ('Minimum fee (4 bags or fewer)', 7.00, 1, false),
--     ('Pick-up truck / trailer — full load', 38.00, 2, false),
--     ('Pick-up truck / trailer — partial load', 19.00, 3, false),
--     ('One-ton truck', 64.00, 4, false),
--     ('Fridge or freezer (each)', 40.00, 5, true),
--     ('Untarped load surcharge', 30.00, 6, true)
--   ) as t(label, price, sort_order, is_addon);
