-- docs/schema/portal-report-schedules-migration.sql
--
-- Company Portal follow-up, step 5: emailing completed Portal documents to a
-- department, on demand or on a schedule.
--
-- One row is one schedule a supervisor set up: which department's documents
-- it covers, how often it goes out, and who gets it. The recipients are the
-- department's active supervisors (when include_department_supervisors is
-- on) plus any addresses the supervisor added by hand. Those hand-added
-- addresses are stored ENCRYPTED in recipients_encrypted (AES-256-GCM via
-- server-lib/fieldCrypto.js, a JSON array of email strings), the same way
-- roster.email is.
--
-- last_sent_at is how the daily cron (api/cron-portal-reports.js) decides
-- what is new: a run covers records created since the last send, and a
-- schedule is skipped if it already went out today (UTC). Department is
-- validated in application code against server-lib/portalDepartments.js, not
-- a check constraint, like every other department column in this feature.
--
-- RLS on with no policies: the deny-by-default backstop every table has.

create table if not exists public.portal_report_schedules (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  department text not null,
  frequency text not null check (frequency in ('daily', 'weekly')),
  -- 0 = Sunday ... 6 = Saturday, UTC. Only meaningful for weekly.
  weekday smallint check (weekday between 0 and 6),
  include_department_supervisors boolean not null default true,
  recipients_encrypted text,
  active boolean not null default true,
  last_sent_at timestamptz,
  created_by_roster_id bigint references public.roster(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists portal_report_schedules_company_id_idx on public.portal_report_schedules(company_id);
create index if not exists portal_report_schedules_active_idx on public.portal_report_schedules(active) where active;

alter table public.portal_report_schedules enable row level security;
