-- Schema for worker safety certification tracking ("onboarding wallet",
-- Phase 1 — see the Barney-boardroom session that scoped this). Each
-- roster member (worker or supervisor) can have zero or more uploaded
-- certs/tickets tied to them, scoped to the company that invited them —
-- deliberately NOT a cross-company/portable identity (see decision below).
--
-- APPLY via mcp__Supabase__apply_migration against project
-- wzyvbtzxxdcxgvbkcqmt, migration name "worker_certifications_schema".
--
-- Open-question answers this migration assumes (confirmed before Phase 1
-- started, not guessed at mid-build):
--   1. Retention: cert rows are retained when a roster member is
--      deactivated (no cascade delete off `active` going false) — a
--      company's training/compliance records need to survive someone
--      leaving. Only an explicit roster row delete (already cascades via
--      roster_id references roster(id) on delete cascade) removes them.
--   2. v1 scope: storage + a computed/displayed status only. No push/
--      email expiry reminders yet — that's Phase 3, gated on this data
--      model shipping first.
--   3. Portability: per-company only. A worker's uploads belong to the
--      company that owns the roster row; nothing here lets a second
--      company read another company's worker_certifications rows even if
--      the same human works both jobs. Cross-company re-sharing is an
--      explicit future phase with its own worker-consent design, not
--      automatic visibility.

-- ── roster: opt-in wallet flag ──────────────────────────────────────────
-- Defaults false so no existing company suddenly exposes an upload flow
-- it didn't ask for — same pattern as roster_enabled on companies.
alter table roster
  add column if not exists wallet_enabled boolean not null default false;

-- ── worker_certifications ────────────────────────────────────────────────
-- One row per uploaded cert/ticket. company_id is denormalized off
-- roster_id (rather than joined through roster on every query) so every
-- other company-scoped table in this project follows the same
-- directly-filterable shape api/*.js handlers already expect
-- (tenant-scope-reviewer checks for exactly this).
create table if not exists worker_certifications (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  roster_id bigint not null references roster(id) on delete cascade,
  cert_type text not null,
  cert_name text not null,
  issue_date date,
  expiry_date date,
  file_path text not null,
  uploaded_by_role text not null default 'worker', -- 'worker' | 'supervisor' | 'admin'
  created_at timestamptz not null default now()
);
create index if not exists worker_certifications_company_id_idx
  on worker_certifications (company_id);
create index if not exists worker_certifications_roster_id_idx
  on worker_certifications (roster_id);

-- ── RLS: deny-by-default backstop, matching every other table in this
-- project (see README's Architecture section) — api/certifications.js's
-- service-role key is the real access-control boundary, this is the
-- safety net if the anon key were ever queried directly.
alter table worker_certifications enable row level security;

-- ── Storage: private bucket for cert files (apply once, then leave to
-- the dashboard/API — do not re-run) ────────────────────────────────────
-- insert into storage.buckets (id, name, public)
--   values ('worker-certifications', 'worker-certifications', false)
--   on conflict (id) do nothing;

-- ── Phase 2: onboarding-wallet invite links ──────────────────────────────
-- APPLIED as a follow-up migration, "worker_certifications_wallet_invite".
-- A raw random token (server-lib/onboardingHelpers.js's randomToken,
-- unhashed) stored directly on the roster row, exactly like
-- onboarding_requests.claim_token — looked up by equality, not decoded.
-- Single-use: api/login.js's redeem_wallet_invite clears both columns the
-- moment the link is opened, then hands back an ordinary signed session
-- (same shape as roster_login's) that's valid on its own for the rest of
-- its normal TTL. Generating a new invite (api/companydata.js's
-- create_wallet_invite) overwrites any unused prior token for that person.
alter table roster
  add column if not exists wallet_invite_token text,
  add column if not exists wallet_invite_token_expires_at timestamptz;

create unique index if not exists roster_wallet_invite_token_idx
  on roster (wallet_invite_token) where wallet_invite_token is not null;
